name: Build & Release Gloop

on:
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Instalar dependencias de desarrollo
        run: |
          pip install black flake8 isort

      - name: Build executable
        run: |
          pyinstaller --noconfirm --onefile --windowed src/main.py --name gloop

      - name: Rename artifacts
        run: |
          mkdir dist_release
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/gloop.exe dist_release/gloop-win.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/gloop dist_release/gloop-mac
          else
            mv dist/gloop dist_release/gloop-linux
          fi
        shell: bash

      - name: Verificar formato con black
        run: black --check src

      - name: Verificar imports con isort
        run: isort --check-only src

      - name: Lint con flake8
        run: flake8 src

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: dist_release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
